### ISSUE TITLE
指定修改下载文件的名字？

### ISSUE THREAD

**Issue by RexDu** [agelessman/MCDownloadManager#2]
首先真的非常感谢您的辛苦封装，也很受用！

请问可以指定下载文件的名字吗？
比如：一个PDF的文件名字“XXX简介”

当我下载完保存在本地的名字就改成“XXX简介.pdf”

@RexDu 这个目前不支持，我记下来，只能等下个版本再添加了

**Comment by agelessman** [comment]
你为什么要这么做呢？那个在沙盒中，用户也看不到啊

发自邮洽 (http://mailchat.cn/)

发件人: RexDu
收件人: agelessman/MCDownloadManager
抄送人: Subscribed
2016-12-20 16:58
主 题: [agelessman/MCDownloadManager] 指定修改下载文件的名字？ (#2)

首先真的非常感谢您的辛苦封装，也很受用！

请问可以指定下载文件的名字吗？
比如：一个PDF的文件名字“XXX简介”

当我下载完保存在本地的名字就改成“XXX简介.pdf”

**Comment by RexDu** [comment]
有一种场景是这样的 app下载到沙盒的PDF或者word文件 再用UIDocumentInteractionController 转发到微信的时候这个名字就体现出来了

我读了下您的代码 貌似很容易扩展这个需求 写的真不错
