### ISSUE TITLE
建议加个下载速度的展示

### ISSUE THREAD

**Issue by peak77** [agelessman/MCDownloadManager#3]

**Comment by agelessman** [comment]
@peakerWu 这个功能我已经加上了，有时间你下载最新的看看，有什么问题，再联系我

**Comment by peak77** [comment]
好的  马上下载看看。

**Comment by peak77** [comment]
好的  马上下载看看。

**Comment by peak77** [comment]
好的，真的好棒，加油哥们


来自 魅族 MX4

-------- 原始邮件 --------
发件人："M.C" <notifications@github.com>
时间：周四 12月22日 09:38
收件人：agelessman/MCDownloadManager <MCDownloadManager@noreply.github.com>
抄送：peakerWu <wulong9347@163.com>,Mention <mention@noreply.github.com>
主题：Re: [agelessman/MCDownloadManager] 建议加个下载速度的展示 (#3)
