### ISSUE TITLE
下载完成后应该返回文件的本地地址，现在返回的是服务器地址

### ISSUE THREAD

**Issue by wendymylove** [agelessman/MCDownloadManager#5]
。。。

**Comment by agelessman** [comment]
我想的是根据URL 去获取那个receipt ， 然后根据receipt.filePath获取文件的路径
MCDownloadReceipt *receipt = [[MCDownloadManager defaultInstance] downloadReceiptForURL:cell.url];
    UIViewController *vc = [UIApplication sharedApplication].keyWindow.rootViewController;
    MPMoviePlayerViewController *mpc = [[MPMoviePlayerViewController alloc] initWithContentURL:[NSURL fileURLWithPath:receipt.filePath]];
    [vc presentViewController:mpc animated:YES completion:nil];
